### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#150]
- [x] Click event on nav 
- [x] Click on nav map
- [x] Click on type things in text lookup
- [ ] Search for address

**Comment by allthesignals** [comment]
Need GA token from @chriswhong, but I can move ahead with integration.

**Comment by allthesignals** [comment]
I have the GA token, and I have GA tracking events and pages on a branch here: https://github.com/NYCPlanning/labs-community-portal/tree/150-google-analytics

I'm waiting on the last item because we had some debate around how to implement address search, which hasn't happened yet

**Comment by allthesignals** [comment]
@andycochran let's design some other data points we might be interested in because that will affect which click events I track.

So far I can think:
 - Who is searching for an address?
 - Text input (debounced); what are people generally typing? 
 - Text input following a dropdown click
 - Do people navigate through the map or the dropdown more? 
 - How long do people spend on the profile page? 
 - How much time are people spending on different sections of the page? 
 - How many uses reach the end of the Profile page?
 - Are individual users reading multiple profiles or just one? 
 - How many users are downloading the data?

**Comment by andycochran** [comment]
- How do users interact with the section menu? 
  - Which items do they click? 
  - Do they click it when the page is scrolled (to move between sections)? 
- Do users want scrollTop on route change? (Do they quickly toggle between districts to compare a specific stat? Or do they scroll back to the top when they switch?) 
- How do users interact with the section header anchors?
  - Do they click the section header anchors?
  - Tho this doesn't tell us if they actually share the link, so… How many users' first route includes a query parameter? 
  - Aside: Do we want to encourage sharing anchor URLs? Could copy-to-clipboard on click (with text on hover indicating you can do so) be a good UX to improve sharing specific anchors? 
- Do users hover the ranking charts? Do they click them expecting an event?

**Comment by andycochran** [comment]
- Do users hover tooltips?

**Comment by allthesignals** [comment]
@andycochran I am moving these to "advanced analytics" issue because I worry about time and current branch achieves core of issue.
