### ISSUE TITLE
Implement wireframe for cd pages

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#7]
- [ ] Side panel of basic data points
![Screen Shot 2017-08-02 at 2.51.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f16b7191a37af1172a4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee4d63b5921c03514aebb851dee01ba25834883b3ee8d1ad2f42f67b6d5db1063474f4dcbed5727a29f41c95df64ae7445cad10356bee702431.png)

- [ ] Fixed sticky section/subsection scrollspy
![Screen Shot 2017-08-02 at 3.03.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f16b7191a37bf112284f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ee4d63b5921c03514aebb851dee01ba25834883b3ee8d1ad2f42f67b6d5db1063474f4dcbed5727a29f41c95df64ae64d55a11a3161e2742431.png)

**Comment by allthesignals** [comment]
Loading a CD directly works, but the bounds don't center correctly in application-profile transition or direct to profile transition because the sequence of events are like this:
1. Invalidate map size
2. Set map bounds
3. Render ember wormhole

Ember wormhole is a component used in the profile view, but it's lifecycle events happen after the fact. Either there needs to be a different approach to getting data into a parent route (refactor) or there needs to be a better approach to the sequence of events.

**Comment by andycochran** [comment]
Blocked by https://github.com/NYCPlanning/labs-community-portal/issues/23

**Comment by andycochran** [comment]
No longer blocked by #23. 

However, Sticky isn't working. New branch has sections and sticky menu added: https://github.com/NYCPlanning/labs-community-portal/tree/7-section-nav

**Comment by chriswhong** [comment]
Closed by #46
